/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clarity.clarity;

import java.awt.Color;

/**
 *
 * @author Ann Maria
 */
public class Ad_menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ad_menu.class.getName());

    /**
     * Creates new form Queries
     */
    public Ad_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        St_details_ad = new javax.swing.JButton();
        Fac_details_ad = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        rep_details = new javax.swing.JButton();
        chat_db = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(106, 0, 212));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 0, 212));
        jLabel1.setText("CLARITY");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 0, 212));
        jLabel2.setText("Student & Faculty anonymous QnA");

        St_details_ad.setBackground(new java.awt.Color(106, 0, 212));
        St_details_ad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        St_details_ad.setForeground(new java.awt.Color(255, 255, 255));
        St_details_ad.setText("Student Details");
        St_details_ad.setToolTipText("");
        St_details_ad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        St_details_ad.setBorderPainted(false);
        St_details_ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        St_details_ad.setPreferredSize(new java.awt.Dimension(175, 60));
        St_details_ad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                St_details_adMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                St_details_adMouseExited(evt);
            }
        });
        St_details_ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                St_details_adActionPerformed(evt);
            }
        });

        Fac_details_ad.setBackground(new java.awt.Color(106, 0, 212));
        Fac_details_ad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Fac_details_ad.setForeground(new java.awt.Color(255, 255, 255));
        Fac_details_ad.setText("Faculty Details");
        Fac_details_ad.setToolTipText("");
        Fac_details_ad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Fac_details_ad.setBorderPainted(false);
        Fac_details_ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fac_details_ad.setPreferredSize(new java.awt.Dimension(175, 60));
        Fac_details_ad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Fac_details_adMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Fac_details_adMouseExited(evt);
            }
        });
        Fac_details_ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fac_details_adActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(106, 0, 212));
        back_btn.setText("<");
        back_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.setBorderPainted(false);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        rep_details.setBackground(new java.awt.Color(106, 0, 212));
        rep_details.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        rep_details.setForeground(new java.awt.Color(255, 255, 255));
        rep_details.setText("Report Details");
        rep_details.setToolTipText("");
        rep_details.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rep_details.setBorderPainted(false);
        rep_details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rep_details.setPreferredSize(new java.awt.Dimension(175, 60));
        rep_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rep_detailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rep_detailsMouseExited(evt);
            }
        });
        rep_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep_detailsActionPerformed(evt);
            }
        });

        chat_db.setBackground(new java.awt.Color(106, 0, 212));
        chat_db.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        chat_db.setForeground(new java.awt.Color(255, 255, 255));
        chat_db.setText("Chat Database");
        chat_db.setToolTipText("");
        chat_db.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chat_db.setBorderPainted(false);
        chat_db.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chat_db.setPreferredSize(new java.awt.Dimension(175, 60));
        chat_db.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chat_dbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chat_dbMouseExited(evt);
            }
        });
        chat_db.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chat_dbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fac_details_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(St_details_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rep_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chat_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(100, 100, 100)
                .addComponent(St_details_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Fac_details_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rep_details, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chat_db, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void St_details_adMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_St_details_adMouseEntered
        // TODO add your handling code here:
        St_details_ad.setBackground(new Color(255,255,255));
        St_details_ad.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_St_details_adMouseEntered

    private void St_details_adMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_St_details_adMouseExited
        // TODO add your handling code here:
        St_details_ad.setBackground(new Color(106,0,212));
        St_details_ad.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_St_details_adMouseExited

    private void St_details_adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_St_details_adActionPerformed
        St_details_ad ob= new St_details_ad();
        ob.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_St_details_adActionPerformed

    private void Fac_details_adMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_details_adMouseEntered
        // TODO add your handling code here:
        Fac_details_ad.setBackground(new Color(255,255,255));
        Fac_details_ad.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_Fac_details_adMouseEntered

    private void Fac_details_adMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_details_adMouseExited
        // TODO add your handling code here:
        Fac_details_ad.setBackground(new Color(106,0,212));
        Fac_details_ad.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_Fac_details_adMouseExited

    private void Fac_details_adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fac_details_adActionPerformed
        // TODO add your handling code here:
        Fac_details_ad ob = new Fac_details_ad();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Fac_details_adActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        Ad_login ob = new Ad_login();
        ob.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void rep_detailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rep_detailsMouseEntered
        // TODO add your handling code here:
         rep_details.setBackground(new Color(255,255,255));
        rep_details.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_rep_detailsMouseEntered

    private void rep_detailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rep_detailsMouseExited
        // TODO add your handling code here:
        rep_details.setBackground(new Color(106,0,212));
        rep_details.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_rep_detailsMouseExited

    private void rep_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep_detailsActionPerformed
        // TODO add your handling code here:
        Reports_ad ob = new Reports_ad();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rep_detailsActionPerformed

    private void chat_dbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chat_dbMouseEntered
        // TODO add your handling code here:
         chat_db.setBackground(new Color(255,255,255));
        chat_db.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_chat_dbMouseEntered

    private void chat_dbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chat_dbMouseExited
        // TODO add your handling code here:
        chat_db.setBackground(new Color(106,0,212));
        chat_db.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_chat_dbMouseExited

    private void chat_dbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chat_dbActionPerformed
        // TODO add your handling code here:
        Chat_db ob = new Chat_db();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_chat_dbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ad_menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fac_details_ad;
    private javax.swing.JButton St_details_ad;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton chat_db;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rep_details;
    // End of variables declaration//GEN-END:variables
}
