/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clarity.clarity;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Ann Maria
 */
public class Ask_qs extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ask_qs.class.getName());

    /**
     * Creates new form Ask_qs
     */
    public Ask_qs() {
        initComponents();
        loadFacultyNames();
        
    }
private void loadFacultyNames() {
    String sql = "SELECT name FROM faculty_details ORDER BY name ASC";
    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/clarity", "root", "");
         PreparedStatement pst = con.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        cmbFaculty.removeAllItems();
        cmbFaculty.addItem("Select Faculty"); // ✅ Add this ONCE before the loop

        while (rs.next()) {
            cmbFaculty.addItem(rs.getString("name")); // ✅ Add actual names only
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading faculty names: " + e.getMessage());
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        st_qry_get = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        qry_submit_btn = new javax.swing.JButton();
        cmbFaculty = new javax.swing.JComboBox<>();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(106, 0, 212));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 0, 212));
        jLabel1.setText("CLARITY");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 0, 212));
        jLabel2.setText("Student & Faculty anonymous QnA");

        st_qry_get.setBackground(new java.awt.Color(204, 153, 255));
        st_qry_get.setForeground(new java.awt.Color(255, 255, 255));
        st_qry_get.setPreferredSize(new java.awt.Dimension(150, 100));
        st_qry_get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_qry_getActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 0, 212));
        jLabel3.setText("Enter Your Doubt Below:");

        qry_submit_btn.setBackground(new java.awt.Color(106, 0, 212));
        qry_submit_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        qry_submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        qry_submit_btn.setText("Submit");
        qry_submit_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        qry_submit_btn.setBorderPainted(false);
        qry_submit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        qry_submit_btn.setPreferredSize(new java.awt.Dimension(100, 30));
        qry_submit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                qry_submit_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                qry_submit_btnMouseExited(evt);
            }
        });
        qry_submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qry_submit_btnActionPerformed(evt);
            }
        });

        cmbFaculty.setBackground(new java.awt.Color(106, 0, 212));
        cmbFaculty.setForeground(new java.awt.Color(255, 255, 255));
        cmbFaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select The Faculty", " ", " " }));
        cmbFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFacultyActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(106, 0, 212));
        back_btn.setText("<");
        back_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.setBorderPainted(false);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_btnMouseExited(evt);
            }
        });
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(qry_submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(st_qry_get, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(cmbFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(st_qry_get, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(qry_submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void st_qry_getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_qry_getActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_qry_getActionPerformed

    private void qry_submit_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qry_submit_btnMouseEntered
        // TODO add your handling code here:
        qry_submit_btn.setBackground(new Color
        (255,255,255));
        qry_submit_btn.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_qry_submit_btnMouseEntered

    private void qry_submit_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qry_submit_btnMouseExited
        // TODO add your handling code here:
        qry_submit_btn.setBackground(new Color(106,0,212));
        qry_submit_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_qry_submit_btnMouseExited

    private void qry_submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qry_submit_btnActionPerformed
String facultyName = cmbFaculty.getSelectedItem().toString();
    String queryText = st_qry_get.getText().trim();
    int studentId = Integer.parseInt(Datas.st_uname_sp_get); 
    String st_year = Datas.get_Year;

    if (queryText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter your query.");
        return;
    }

    // Generate session ID
    String prefix = "Y1-" + LocalDate.now().format(DateTimeFormatter.BASIC_ISO_DATE); // e.g., Y1-20250906
    String sqlGetLast = "SELECT session_id FROM queries WHERE session_id LIKE ? ORDER BY session_id DESC LIMIT 1";

    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/clarity", "root", "");
         PreparedStatement pstLast = con.prepareStatement(sqlGetLast)) {

        pstLast.setString(1, prefix + "%");
        ResultSet rs = pstLast.executeQuery();

        int nextSeq = 1;
        if (rs.next()) {
            String lastId = rs.getString("session_id");
            String[] parts = lastId.split("-");
            nextSeq = Integer.parseInt(parts[2]) + 1;
        }

        String newSessionId = prefix + "-" + String.format("%03d", nextSeq);

        // Insert query
        String sqlInsert = "INSERT INTO queries (session_id, student_id, faculty_name, query_text, year) VALUES (?, ?, ?, ?,?)";
        try (PreparedStatement pstInsert = con.prepareStatement(sqlInsert)) {
            pstInsert.setString(1, newSessionId);
            pstInsert.setInt(2, studentId);
            pstInsert.setString(3, facultyName);
            pstInsert.setString(4, queryText);
            pstInsert.setString(5, st_year);
            
            

            int rows = pstInsert.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Query submitted successfully!");
                st_qry_get.setText(""); // clear textbox
            } else {
                JOptionPane.showMessageDialog(this, "Failed to submit query.");
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }

    }//GEN-LAST:event_qry_submit_btnActionPerformed

    private void cmbFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFacultyActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbFacultyActionPerformed

    private void back_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnMouseEntered

    private void back_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnMouseExited

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
    St_menu ob  = new St_menu();
    ob.setVisible(true);
    this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ask_qs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JComboBox<String> cmbFaculty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton qry_submit_btn;
    private javax.swing.JTextField st_qry_get;
    // End of variables declaration//GEN-END:variables
}
