/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clarity.clarity;

import java.awt.Color;

/**
 *
 * @author Ann Maria
 */
public class Fac_menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Fac_menu.class.getName());

    /**
     * Creates new form Fac_menu
     */
    public Fac_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        yr1_btn = new javax.swing.JButton();
        yr2_btn = new javax.swing.JButton();
        yr4_btn = new javax.swing.JButton();
        yr3_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        yr1_btn.setBackground(new java.awt.Color(106, 0, 212));
        yr1_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        yr1_btn.setForeground(new java.awt.Color(255, 255, 255));
        yr1_btn.setText("1st year");
        yr1_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yr1_btn.setBorderPainted(false);
        yr1_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yr1_btn.setPreferredSize(new java.awt.Dimension(175, 60));
        yr1_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yr1_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yr1_btnMouseExited(evt);
            }
        });
        yr1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yr1_btnActionPerformed(evt);
            }
        });

        yr2_btn.setBackground(new java.awt.Color(106, 0, 212));
        yr2_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        yr2_btn.setForeground(new java.awt.Color(255, 255, 255));
        yr2_btn.setText("2nd year");
        yr2_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yr2_btn.setBorderPainted(false);
        yr2_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yr2_btn.setPreferredSize(new java.awt.Dimension(175, 60));
        yr2_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yr2_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yr2_btnMouseExited(evt);
            }
        });
        yr2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yr2_btnActionPerformed(evt);
            }
        });

        yr4_btn.setBackground(new java.awt.Color(106, 0, 212));
        yr4_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        yr4_btn.setForeground(new java.awt.Color(255, 255, 255));
        yr4_btn.setText("4th year");
        yr4_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yr4_btn.setBorderPainted(false);
        yr4_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yr4_btn.setPreferredSize(new java.awt.Dimension(175, 60));
        yr4_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yr4_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yr4_btnMouseExited(evt);
            }
        });
        yr4_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yr4_btnActionPerformed(evt);
            }
        });

        yr3_btn.setBackground(new java.awt.Color(106, 0, 212));
        yr3_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        yr3_btn.setForeground(new java.awt.Color(255, 255, 255));
        yr3_btn.setText("3rd year");
        yr3_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yr3_btn.setBorderPainted(false);
        yr3_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yr3_btn.setPreferredSize(new java.awt.Dimension(175, 60));
        yr3_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yr3_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yr3_btnMouseExited(evt);
            }
        });
        yr3_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yr3_btnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(106, 0, 212));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 0, 212));
        jLabel1.setText("CLARITY");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 0, 212));
        jLabel2.setText("Student & Faculty anonymous QnA");

        back_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(106, 0, 212));
        back_btn.setText("<");
        back_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.setBorderPainted(false);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 168, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(160, 160, 160))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yr1_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yr2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yr4_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yr3_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addComponent(yr1_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(yr2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(yr3_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(yr4_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yr1_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yr1_btnMouseEntered
        // TODO add your handling code here:
        yr1_btn.setBackground(new Color(255,255,255));
        yr1_btn.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_yr1_btnMouseEntered

    private void yr1_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yr1_btnMouseExited
        // TODO add your handling code here:
        yr1_btn.setBackground(new Color(106,0,212));
        yr1_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_yr1_btnMouseExited

    private void yr1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yr1_btnActionPerformed
        Yr_1 ob= new Yr_1();
        ob.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_yr1_btnActionPerformed

    private void yr2_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yr2_btnMouseEntered
        // TODO add your handling code here:
        yr2_btn.setBackground(new Color(255,255,255));
        yr2_btn.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_yr2_btnMouseEntered

    private void yr2_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yr2_btnMouseExited
        // TODO add your handling code here:
        yr2_btn.setBackground(new Color(106,0,212));
        yr2_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_yr2_btnMouseExited

    private void yr2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yr2_btnActionPerformed
        // TODO add your handling code here:
        Yr_2 ob = new Yr_2();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_yr2_btnActionPerformed

    private void yr4_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yr4_btnMouseEntered
        // TODO add your handling code here:
        yr4_btn.setBackground(new Color(255,255,255));
        yr4_btn.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_yr4_btnMouseEntered

    private void yr4_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yr4_btnMouseExited
        // TODO add your handling code here:
        yr4_btn.setBackground(new Color(106,0,212));
        yr4_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_yr4_btnMouseExited

    private void yr4_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yr4_btnActionPerformed
        // TODO add your handling code here:
        Yr_4 ob = new Yr_4();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_yr4_btnActionPerformed

    private void yr3_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yr3_btnMouseEntered
        // TODO add your handling code here:
        yr3_btn.setBackground(new Color(255,255,255));
        yr3_btn.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_yr3_btnMouseEntered

    private void yr3_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yr3_btnMouseExited
        // TODO add your handling code here:
        yr3_btn.setBackground(new Color(106,0,212));
        yr3_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_yr3_btnMouseExited

    private void yr3_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yr3_btnActionPerformed
        // TODO add your handling code here:
        Yr_3 ob = new Yr_3();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_yr3_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        Fac_login ob = new Fac_login();
        ob.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Fac_menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton yr1_btn;
    private javax.swing.JButton yr2_btn;
    private javax.swing.JButton yr3_btn;
    private javax.swing.JButton yr4_btn;
    // End of variables declaration//GEN-END:variables
}
