/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clarity.clarity;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author irfan
 */
public class Fac_details_ad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Fac_details_ad.class.getName());

    /**
     * Creates new form Fac_details_ad
     */
    public Fac_details_ad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tableScrollPane = new javax.swing.JScrollPane();
        FacDetails_table = new javax.swing.JTable();
        Fac_fetchDetails = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        Fac_addDetails = new javax.swing.JButton();
        Fac_addDetails1 = new javax.swing.JButton();
        Upt_fac = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(106, 0, 212));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 0, 212));
        jLabel1.setText("CLARITY");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 0, 212));
        jLabel2.setText("Student & Faculty anonymous QnA");

        tableScrollPane.setForeground(new java.awt.Color(106, 0, 212));

        FacDetails_table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FacDetails_table.setForeground(new java.awt.Color(106, 0, 212));
        FacDetails_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Name", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPane.setViewportView(FacDetails_table);

        Fac_fetchDetails.setBackground(new java.awt.Color(106, 0, 212));
        Fac_fetchDetails.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Fac_fetchDetails.setForeground(new java.awt.Color(255, 255, 255));
        Fac_fetchDetails.setText("Fetch Details");
        Fac_fetchDetails.setToolTipText("");
        Fac_fetchDetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Fac_fetchDetails.setBorderPainted(false);
        Fac_fetchDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fac_fetchDetails.setPreferredSize(new java.awt.Dimension(175, 60));
        Fac_fetchDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Fac_fetchDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Fac_fetchDetailsMouseExited(evt);
            }
        });
        Fac_fetchDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fac_fetchDetailsActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(106, 0, 212));
        back_btn.setText("<");
        back_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.setBorderPainted(false);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Fac_fetchDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(Fac_fetchDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        Fac_addDetails.setBackground(new java.awt.Color(106, 0, 212));
        Fac_addDetails.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Fac_addDetails.setForeground(new java.awt.Color(255, 255, 255));
        Fac_addDetails.setText("Add faculty\n\n");
        Fac_addDetails.setToolTipText("");
        Fac_addDetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Fac_addDetails.setBorderPainted(false);
        Fac_addDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fac_addDetails.setPreferredSize(new java.awt.Dimension(175, 60));
        Fac_addDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Fac_addDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Fac_addDetailsMouseExited(evt);
            }
        });
        Fac_addDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fac_addDetailsActionPerformed(evt);
            }
        });

        Fac_addDetails1.setBackground(new java.awt.Color(255, 0, 0));
        Fac_addDetails1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Fac_addDetails1.setForeground(new java.awt.Color(255, 255, 255));
        Fac_addDetails1.setText("Delete Faculty");
        Fac_addDetails1.setToolTipText("");
        Fac_addDetails1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Fac_addDetails1.setBorderPainted(false);
        Fac_addDetails1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fac_addDetails1.setPreferredSize(new java.awt.Dimension(175, 60));
        Fac_addDetails1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Fac_addDetails1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Fac_addDetails1MouseExited(evt);
            }
        });
        Fac_addDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fac_addDetails1ActionPerformed(evt);
            }
        });

        Upt_fac.setBackground(new java.awt.Color(106, 0, 212));
        Upt_fac.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Upt_fac.setForeground(new java.awt.Color(255, 255, 255));
        Upt_fac.setText("Update   ");
        Upt_fac.setToolTipText("");
        Upt_fac.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Upt_fac.setBorderPainted(false);
        Upt_fac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Upt_fac.setPreferredSize(new java.awt.Dimension(175, 60));
        Upt_fac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Upt_facMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Upt_facMouseExited(evt);
            }
        });
        Upt_fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Upt_facActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Upt_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Fac_addDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Fac_addDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fac_addDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Upt_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fac_addDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Fac_fetchDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_fetchDetailsMouseEntered
        // TODO add your handling code here:
        Fac_fetchDetails.setBackground(new Color(255,255,255));
        Fac_fetchDetails.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_Fac_fetchDetailsMouseEntered

    private void Fac_fetchDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_fetchDetailsMouseExited
        // TODO add your handling code here:
        Fac_fetchDetails.setBackground(new Color(106,0,212));
        Fac_fetchDetails.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_Fac_fetchDetailsMouseExited

    private void Fac_fetchDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fac_fetchDetailsActionPerformed
        // TODO add your handling code here:
        try {
            // Load JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Connect to database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/clarity", "root", "");

            // SQL query
            String query = "SELECT * FROM faculty_details WHERE status = 'active'";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            // Get table model
            DefaultTableModel model = (DefaultTableModel) FacDetails_table.getModel();
            model.setRowCount(0); // Clear existing rows

            // Populate table
            while (rs.next()) {
                int id = rs.getInt("No");
                String uname = rs.getString("Name");
                int pword = rs.getInt("Password");
                

                model.addRow(new Object[]{id, uname, pword});
            }

            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage());
        }
    }//GEN-LAST:event_Fac_fetchDetailsActionPerformed

    private void Fac_addDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_addDetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Fac_addDetailsMouseEntered

    private void Fac_addDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_addDetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Fac_addDetailsMouseExited

    private void Fac_addDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fac_addDetailsActionPerformed
        // TODO add your handling code here:
        Add_faculty ob = new Add_faculty();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Fac_addDetailsActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
       Ad_menu ob = new Ad_menu();
        ob.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void Fac_addDetails1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_addDetails1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Fac_addDetails1MouseEntered

    private void Fac_addDetails1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_addDetails1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Fac_addDetails1MouseExited

    private void Fac_addDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fac_addDetails1ActionPerformed
        // TODO add your handling code here:
    int row = FacDetails_table.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a faculty to delete.");
        return;
    }

    String facultyName = FacDetails_table.getValueAt(row, 0).toString(); // assuming column 0 is faculty_name

    int confirm = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to delete this faculty?",
        "Confirm Delete", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        String sql = "UPDATE faculty_details SET status = 'deleted' WHERE faculty_name = ?";

        try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/clarity", "root", "");
             PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setString(1, facultyName);
            int rows = pst.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Faculty marked as deleted.");
                // Optionally refresh table
                //fetchFaculty(); // your method to reload active faculty
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error deleting faculty: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_Fac_addDetails1ActionPerformed

    private void Upt_facMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Upt_facMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Upt_facMouseEntered

    private void Upt_facMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Upt_facMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Upt_facMouseExited

    private void Upt_facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upt_facActionPerformed
        // TODO add your handling code here:
   int row = FacDetails_table.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a faculty to update.");
        return;
    }

    String facultyName = FacDetails_table.getValueAt(row, 1).toString(); // assuming column 1 is Name

    // 🔹 Prompt for new password
    JPasswordField pwdField = new JPasswordField();
    int option = JOptionPane.showConfirmDialog(this, pwdField, 
        "Enter New Password for " + facultyName, JOptionPane.OK_CANCEL_OPTION);

    if (option == JOptionPane.OK_OPTION) {
        String newPassword = new String(pwdField.getPassword()).trim();

        if (newPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password cannot be empty.");
            return;
        }

        String sql = "UPDATE faculty_details SET Password = ? WHERE Name = ?";

        try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/clarity", "root", "");
             PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setString(1, newPassword);
            pst.setString(2, facultyName);

            int rows = pst.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Password updated successfully.");
                //fetchFaculty(); // refresh table
            } else {
                JOptionPane.showMessageDialog(this, "Update failed.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }



    }//GEN-LAST:event_Upt_facActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Fac_details_ad().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FacDetails_table;
    private javax.swing.JButton Fac_addDetails;
    private javax.swing.JButton Fac_addDetails1;
    private javax.swing.JButton Fac_fetchDetails;
    private javax.swing.JButton Upt_fac;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
