/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clarity.clarity;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author irfan
 */
public class FacultyRespond extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FacultyRespond.class.getName());

    /**
     * Creates new form FacultyRespond
     */
    public FacultyRespond() {
        initComponents();
        sess_id.setText(Datas.selectedSessionId);
        st_qry_view.setText(Datas.selectedQueryText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        st_qry_view = new javax.swing.JTextField();
        st_ans_view = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sess_id = new javax.swing.JTextField();
        session_id_view = new javax.swing.JLabel();
        report_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 0, 212));
        jLabel2.setText("Student & Faculty anonymous QnA");

        jLabel1.setBackground(new java.awt.Color(106, 0, 212));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 0, 212));
        jLabel1.setText("CLARITY");

        st_qry_view.setEditable(false);
        st_qry_view.setBackground(new java.awt.Color(204, 153, 255));
        st_qry_view.setForeground(new java.awt.Color(255, 255, 255));
        st_qry_view.setPreferredSize(new java.awt.Dimension(150, 100));
        st_qry_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_qry_viewActionPerformed(evt);
            }
        });

        st_ans_view.setBackground(new java.awt.Color(229, 229, 229));
        st_ans_view.setForeground(new java.awt.Color(106, 0, 212));
        st_ans_view.setPreferredSize(new java.awt.Dimension(150, 100));
        st_ans_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_ans_viewActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 0, 212));
        jLabel3.setText("Query");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 0, 212));
        jLabel4.setText("Your Response:");

        sess_id.setEditable(false);
        sess_id.setBackground(new java.awt.Color(204, 153, 255));
        sess_id.setForeground(new java.awt.Color(255, 255, 255));
        sess_id.setMinimumSize(new java.awt.Dimension(100, 30));
        sess_id.setPreferredSize(new java.awt.Dimension(100, 30));
        sess_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sess_idActionPerformed(evt);
            }
        });

        session_id_view.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        session_id_view.setForeground(new java.awt.Color(106, 0, 212));
        session_id_view.setText("Session ID:");

        report_btn.setBackground(new java.awt.Color(255, 0, 0));
        report_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        report_btn.setForeground(new java.awt.Color(255, 255, 255));
        report_btn.setText("Report");
        report_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        report_btn.setBorderPainted(false);
        report_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        report_btn.setPreferredSize(new java.awt.Dimension(100, 30));
        report_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                report_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                report_btnMouseExited(evt);
            }
        });
        report_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_btnActionPerformed(evt);
            }
        });

        submit_btn.setBackground(new java.awt.Color(0, 204, 51));
        submit_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("submit");
        submit_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submit_btn.setBorderPainted(false);
        submit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_btn.setPreferredSize(new java.awt.Dimension(100, 30));
        submit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submit_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submit_btnMouseExited(evt);
            }
        });
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(106, 0, 212));
        back_btn.setText("<");
        back_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.setBorderPainted(false);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_btnMouseExited(evt);
            }
        });
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel1))
                                            .addComponent(jLabel2)))
                                    .addComponent(st_qry_view, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(0, 108, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(st_ans_view, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(session_id_view)
                                .addGap(18, 18, 18)
                                .addComponent(sess_id, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(report_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(session_id_view)
                    .addComponent(sess_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(st_qry_view, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(st_ans_view, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(report_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void st_qry_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_qry_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_qry_viewActionPerformed

    private void st_ans_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_ans_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_ans_viewActionPerformed

    private void sess_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sess_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sess_idActionPerformed

    private void report_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_btnMouseEntered
        // TODO add your handling code here:
        report_btn.setBackground(new Color(255,255,255));
        report_btn.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_report_btnMouseEntered

    private void report_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_btnMouseExited
        // TODO add your handling code here:
        report_btn.setBackground(new Color(255,0,0));
        report_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_report_btnMouseExited

    private void report_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_btnActionPerformed
        // TODO add your handling code here:
         String sessionId = Datas.selectedSessionId;
    String facultyName = Datas.loggedInFacultyName;

    // Ask faculty for a reason
    String reason = JOptionPane.showInputDialog(this, "Enter reason for reporting:");

    if (reason == null || reason.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Report cancelled. Reason is required.");
        return;
    }

    String sql = "INSERT INTO reports (session_id, reported_by, reason) VALUES (?, ?, ?)";

    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/clarity", "root", "");
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, sessionId);
        pst.setString(2, facultyName);
        pst.setString(3, reason);

        int rows = pst.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Query reported to Admin successfully!");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error reporting query: " + e.getMessage());
    }


    }//GEN-LAST:event_report_btnActionPerformed

    private void submit_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_btnMouseEntered
        // TODO add your handling code here:
        submit_btn.setBackground(new Color(255,255,255));
        submit_btn.setForeground(new Color(0,204,51));
    }//GEN-LAST:event_submit_btnMouseEntered

    private void submit_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_btnMouseExited
        // TODO add your handling code here:
        submit_btn.setBackground(new Color(0,204,51));
        submit_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_submit_btnMouseExited

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        String sessionId = sess_id.getText().trim();         // from Datas or form field
    String responseText = st_ans_view.getText().trim();       // faculty's reply
    String status = "Resolved";                               // or get from dropdown if needed

    if (responseText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a response before submitting.");
        return;
    }

    String sql = "UPDATE queries SET faculty_response = ?, responded_at = NOW(), status = ? WHERE session_id = ?";

    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/clarity", "root", "");
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, responseText);
        pst.setString(2, status);
        pst.setString(3, sessionId);

        int rows = pst.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Response submitted successfully!");
            st_ans_view.setText(""); // clear response box
        } else {
            JOptionPane.showMessageDialog(this, "Failed to submit response. Check session ID.");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }

    }//GEN-LAST:event_submit_btnActionPerformed

    private void back_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnMouseEntered

    private void back_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnMouseExited

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        Fac_menu ob  = new Fac_menu();
        ob.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FacultyRespond().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton report_btn;
    private javax.swing.JTextField sess_id;
    private javax.swing.JLabel session_id_view;
    private javax.swing.JTextField st_ans_view;
    private javax.swing.JTextField st_qry_view;
    private javax.swing.JButton submit_btn;
    // End of variables declaration//GEN-END:variables
}
