/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clarity.clarity;

import java.awt.Color;

/**
 *
 * @author Ann Maria
 */
public class MainMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        st_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fac_login = new javax.swing.JButton();
        admin_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        st_login.setBackground(new java.awt.Color(106, 0, 212));
        st_login.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        st_login.setForeground(new java.awt.Color(255, 255, 255));
        st_login.setText("Student Login");
        st_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        st_login.setBorderPainted(false);
        st_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        st_login.setPreferredSize(new java.awt.Dimension(175, 60));
        st_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                st_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                st_loginMouseExited(evt);
            }
        });
        st_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_loginActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(106, 0, 212));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 0, 212));
        jLabel1.setText("CLARITY");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 0, 212));
        jLabel2.setText("Student & Faculty anonymous QnA");

        fac_login.setBackground(new java.awt.Color(106, 0, 212));
        fac_login.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        fac_login.setForeground(new java.awt.Color(255, 255, 255));
        fac_login.setText("Faculty Login");
        fac_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fac_login.setBorderPainted(false);
        fac_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fac_login.setPreferredSize(new java.awt.Dimension(175, 60));
        fac_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fac_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fac_loginMouseExited(evt);
            }
        });
        fac_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fac_loginActionPerformed(evt);
            }
        });

        admin_login.setBackground(new java.awt.Color(106, 0, 212));
        admin_login.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        admin_login.setForeground(new java.awt.Color(255, 255, 255));
        admin_login.setText("Admin Login");
        admin_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        admin_login.setBorderPainted(false);
        admin_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin_login.setPreferredSize(new java.awt.Dimension(175, 60));
        admin_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admin_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                admin_loginMouseExited(evt);
            }
        });
        admin_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(163, 163, 163))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(st_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fac_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(admin_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(79, 79, 79)
                .addComponent(st_login, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(fac_login, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(admin_login, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void st_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_st_loginMouseEntered
        // TODO add your handling code here:
        st_login.setBackground(new Color(255,255,255));
        st_login.setForeground(new Color(106,0,212));

    }//GEN-LAST:event_st_loginMouseEntered

    private void st_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_st_loginMouseExited
        // TODO add your handling code here:
        st_login.setBackground(new Color(106,0,212));
        st_login.setForeground(new Color(255,255,255));

    }//GEN-LAST:event_st_loginMouseExited

    private void st_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_loginActionPerformed
        St_login ob= new St_login();
        ob.setVisible(true);
        this.dispose(); 

        // TODO add your handling code here:
    }//GEN-LAST:event_st_loginActionPerformed

    private void fac_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fac_loginMouseEntered
        // TODO add your handling code here:
        fac_login.setBackground(new Color(255,255,255));
        fac_login.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_fac_loginMouseEntered

    private void fac_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fac_loginMouseExited
        // TODO add your handling code here:
        fac_login.setBackground(new Color(106,0,212));
        fac_login.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_fac_loginMouseExited

    private void fac_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fac_loginActionPerformed
        // TODO add your handling code here:
        Fac_login ob= new Fac_login();
        ob.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_fac_loginActionPerformed

    private void admin_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_loginMouseEntered
        // TODO add your handling code here:
        admin_login.setBackground(new Color(255,255,255));
        admin_login.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_admin_loginMouseEntered

    private void admin_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_loginMouseExited
        // TODO add your handling code here:
        admin_login.setBackground(new Color(106,0,212));
        admin_login.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_admin_loginMouseExited

    private void admin_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_loginActionPerformed
        // TODO add your handling code here:
        Ad_login ob = new Ad_login();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_admin_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_login;
    private javax.swing.JButton fac_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton st_login;
    // End of variables declaration//GEN-END:variables
}
