/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clarity.clarity;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author irfan
 */
public class St_details_ad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(St_details_ad.class.getName());

    /**
     * Creates new form St_details_ad
     */
    public St_details_ad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tableScrollPane = new javax.swing.JScrollPane();
        StDetails_table = new javax.swing.JTable();
        St_details_ad = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        Fac_addDetails = new javax.swing.JButton();
        Fac_addDetails1 = new javax.swing.JButton();
        Fac_addDetails2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(106, 0, 212));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 0, 212));
        jLabel1.setText("CLARITY");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 0, 212));
        jLabel2.setText("Student & Faculty anonymous QnA");

        tableScrollPane.setForeground(new java.awt.Color(106, 0, 212));

        StDetails_table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StDetails_table.setForeground(new java.awt.Color(106, 0, 212));
        StDetails_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "username", "password", "year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPane.setViewportView(StDetails_table);

        St_details_ad.setBackground(new java.awt.Color(106, 0, 212));
        St_details_ad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        St_details_ad.setForeground(new java.awt.Color(255, 255, 255));
        St_details_ad.setText("Fetch Details");
        St_details_ad.setToolTipText("");
        St_details_ad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        St_details_ad.setBorderPainted(false);
        St_details_ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        St_details_ad.setPreferredSize(new java.awt.Dimension(175, 60));
        St_details_ad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                St_details_adMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                St_details_adMouseExited(evt);
            }
        });
        St_details_ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                St_details_adActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(106, 0, 212));
        back_btn.setText("<");
        back_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.setBorderPainted(false);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel1))))
                            .addComponent(St_details_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(St_details_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        Fac_addDetails.setBackground(new java.awt.Color(106, 0, 212));
        Fac_addDetails.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Fac_addDetails.setForeground(new java.awt.Color(255, 255, 255));
        Fac_addDetails.setText("Add Student  ");
        Fac_addDetails.setToolTipText("");
        Fac_addDetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Fac_addDetails.setBorderPainted(false);
        Fac_addDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fac_addDetails.setPreferredSize(new java.awt.Dimension(175, 60));
        Fac_addDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Fac_addDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Fac_addDetailsMouseExited(evt);
            }
        });
        Fac_addDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fac_addDetailsActionPerformed(evt);
            }
        });

        Fac_addDetails1.setBackground(new java.awt.Color(255, 0, 51));
        Fac_addDetails1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Fac_addDetails1.setForeground(new java.awt.Color(255, 255, 255));
        Fac_addDetails1.setText("Delete student");
        Fac_addDetails1.setToolTipText("");
        Fac_addDetails1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Fac_addDetails1.setBorderPainted(false);
        Fac_addDetails1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fac_addDetails1.setPreferredSize(new java.awt.Dimension(175, 60));
        Fac_addDetails1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Fac_addDetails1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Fac_addDetails1MouseExited(evt);
            }
        });
        Fac_addDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fac_addDetails1ActionPerformed(evt);
            }
        });

        Fac_addDetails2.setBackground(new java.awt.Color(106, 0, 212));
        Fac_addDetails2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Fac_addDetails2.setForeground(new java.awt.Color(255, 255, 255));
        Fac_addDetails2.setText("Update   ");
        Fac_addDetails2.setToolTipText("");
        Fac_addDetails2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Fac_addDetails2.setBorderPainted(false);
        Fac_addDetails2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fac_addDetails2.setPreferredSize(new java.awt.Dimension(175, 60));
        Fac_addDetails2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Fac_addDetails2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Fac_addDetails2MouseExited(evt);
            }
        });
        Fac_addDetails2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fac_addDetails2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Fac_addDetails2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Fac_addDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Fac_addDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fac_addDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fac_addDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fac_addDetails2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void St_details_adMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_St_details_adMouseEntered
        // TODO add your handling code here:
        St_details_ad.setBackground(new Color(255,255,255));
        St_details_ad.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_St_details_adMouseEntered

    private void St_details_adMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_St_details_adMouseExited
        // TODO add your handling code here:
        St_details_ad.setBackground(new Color(106,0,212));
        St_details_ad.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_St_details_adMouseExited

    private void St_details_adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_St_details_adActionPerformed
    // TODO add your handling code here:
    try {
    
    Class.forName("com.mysql.cj.jdbc.Driver");

   
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/clarity", "root", "");

    
    String query = "SELECT * FROM student_details WHERE status = 'active'";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

    // Get table model
        DefaultTableModel model = (DefaultTableModel) StDetails_table.getModel();
    model.setRowCount(0); // Clear existing rows

    // Populate table
    while (rs.next()) {
        int uname = rs.getInt("username");
        int pword = rs.getInt("password");
        String year = rs.getString("year");
        


        model.addRow(new Object[]{uname, pword, year});
    }

    conn.close();
} catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage());
}
    }//GEN-LAST:event_St_details_adActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        Ad_menu ob = new Ad_menu();
        ob.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void Fac_addDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_addDetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Fac_addDetailsMouseEntered

    private void Fac_addDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_addDetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Fac_addDetailsMouseExited

    private void Fac_addDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fac_addDetailsActionPerformed
        // TODO add your handling code here:
        Add_student ob = new Add_student();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Fac_addDetailsActionPerformed

    private void Fac_addDetails1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_addDetails1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Fac_addDetails1MouseEntered

    private void Fac_addDetails1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_addDetails1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Fac_addDetails1MouseExited

    private void Fac_addDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fac_addDetails1ActionPerformed
        // TODO add your handling code here:
        
    int row = StDetails_table.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a student to delete.");
        return;
    }

    String studentId = StDetails_table.getValueAt(row, 0).toString(); // assuming column 0 is username

    int confirm = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to delete this student?",
        "Confirm Delete", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        String sql = "UPDATE student_details SET status = 'deleted' WHERE username = ?";

        try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/clarity", "root", "");
             PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setString(1, studentId);
            int rows = pst.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Student marked as deleted.");
                // Optionally refresh table
                //fetchStudents(); // your method to reload active students
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error deleting student: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_Fac_addDetails1ActionPerformed

    private void Fac_addDetails2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_addDetails2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Fac_addDetails2MouseEntered

    private void Fac_addDetails2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fac_addDetails2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Fac_addDetails2MouseExited

    private void Fac_addDetails2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fac_addDetails2ActionPerformed
        // TODO add your handling code here:
        int row = StDetails_table.getSelectedRow();

if (row != -1) {
    String studentId = StDetails_table.getValueAt(row, 0).toString();
    UpdateStudentDialog dialog = new UpdateStudentDialog(this, studentId);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
   // fetchStudents(); // refresh table after update
} else {
    JOptionPane.showMessageDialog(this, "Please select a student to update.");
}

    }//GEN-LAST:event_Fac_addDetails2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new St_details_ad().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fac_addDetails;
    private javax.swing.JButton Fac_addDetails1;
    private javax.swing.JButton Fac_addDetails2;
    private javax.swing.JTable StDetails_table;
    private javax.swing.JButton St_details_ad;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
