/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clarity.clarity;

import java.awt.Color;

/**
 *
 * @author Ann Maria
 */
public class St_menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(St_menu.class.getName());

    /**
     * Creates new form St_menu
     */
    public St_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ask_qs_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        view_qs_btn = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ask_qs_btn.setBackground(new java.awt.Color(106, 0, 212));
        ask_qs_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        ask_qs_btn.setForeground(new java.awt.Color(255, 255, 255));
        ask_qs_btn.setText("Ask New Question");
        ask_qs_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ask_qs_btn.setBorderPainted(false);
        ask_qs_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ask_qs_btn.setPreferredSize(new java.awt.Dimension(195, 60));
        ask_qs_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ask_qs_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ask_qs_btnMouseExited(evt);
            }
        });
        ask_qs_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ask_qs_btnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(106, 0, 212));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 0, 212));
        jLabel1.setText("CLARITY");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 0, 212));
        jLabel2.setText("Student & Faculty anonymous QnA");

        view_qs_btn.setBackground(new java.awt.Color(106, 0, 212));
        view_qs_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        view_qs_btn.setForeground(new java.awt.Color(255, 255, 255));
        view_qs_btn.setText("View Past Questions");
        view_qs_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_qs_btn.setBorderPainted(false);
        view_qs_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view_qs_btn.setPreferredSize(new java.awt.Dimension(195, 60));
        view_qs_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                view_qs_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                view_qs_btnMouseExited(evt);
            }
        });
        view_qs_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_qs_btnActionPerformed(evt);
            }
        });

        home_btn.setBackground(new java.awt.Color(106, 0, 212));
        home_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        home_btn.setForeground(new java.awt.Color(255, 255, 255));
        home_btn.setText("Home");
        home_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        home_btn.setBorderPainted(false);
        home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn.setPreferredSize(new java.awt.Dimension(100, 30));
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_btnMouseExited(evt);
            }
        });
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ask_qs_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(view_qs_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(107, 107, 107)
                .addComponent(ask_qs_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(view_qs_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ask_qs_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ask_qs_btnMouseEntered
        // TODO add your handling code here:
        ask_qs_btn.setBackground(new Color(255,255,255));
        ask_qs_btn.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_ask_qs_btnMouseEntered

    private void ask_qs_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ask_qs_btnMouseExited
        // TODO add your handling code here:
        ask_qs_btn.setBackground(new Color(106,0,212));
        ask_qs_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_ask_qs_btnMouseExited

    private void ask_qs_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ask_qs_btnActionPerformed
        // TODO add your handling code here:
        Ask_qs ob = new Ask_qs();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ask_qs_btnActionPerformed

    private void view_qs_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_qs_btnMouseEntered
        // TODO add your handling code here:
        view_qs_btn.setBackground(new Color(255,255,255));
        view_qs_btn.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_view_qs_btnMouseEntered

    private void view_qs_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_qs_btnMouseExited
        // TODO add your handling code here:
        view_qs_btn.setBackground(new Color(106,0,212));
        view_qs_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_view_qs_btnMouseExited

    private void view_qs_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_qs_btnActionPerformed
        // TODO add your handling code here:
        view_qs ob = new view_qs();
        ob.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_view_qs_btnActionPerformed

    private void home_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseEntered
        // TODO add your handling code here:
        home_btn.setBackground(new Color(255,255,255));
        home_btn.setForeground(new Color(106,0,212));
    }//GEN-LAST:event_home_btnMouseEntered

    private void home_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseExited
        // TODO add your handling code here:
        home_btn.setBackground(new Color(106,0,212));
        home_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_home_btnMouseExited

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
        MainMenu ob= new MainMenu();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new St_menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ask_qs_btn;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton view_qs_btn;
    // End of variables declaration//GEN-END:variables
}
