/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clarity.clarity;

import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ann Maria
 */
public class view_qs extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(view_qs.class.getName());

    /**
     * Creates new form view_qs
     */
    public view_qs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        follow_up_btn = new javax.swing.JButton();
        fetch = new javax.swing.JButton();
        resolve_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMyQueries = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 0, 212));
        jLabel2.setText("Student & Faculty anonymous QnA");

        jLabel1.setBackground(new java.awt.Color(106, 0, 212));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 0, 212));
        jLabel1.setText("CLARITY");

        follow_up_btn.setBackground(new java.awt.Color(255, 0, 0));
        follow_up_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        follow_up_btn.setForeground(new java.awt.Color(255, 255, 255));
        follow_up_btn.setText("Ask A Follow Up");
        follow_up_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        follow_up_btn.setBorderPainted(false);
        follow_up_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        follow_up_btn.setPreferredSize(new java.awt.Dimension(100, 30));
        follow_up_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                follow_up_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                follow_up_btnMouseExited(evt);
            }
        });
        follow_up_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                follow_up_btnActionPerformed(evt);
            }
        });

        fetch.setBackground(new java.awt.Color(106, 0, 212));
        fetch.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        fetch.setForeground(new java.awt.Color(255, 255, 255));
        fetch.setText("Fetch Details");
        fetch.setToolTipText("");
        fetch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fetch.setBorderPainted(false);
        fetch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fetch.setPreferredSize(new java.awt.Dimension(175, 60));
        fetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchActionPerformed(evt);
            }
        });

        resolve_btn.setBackground(new java.awt.Color(0, 204, 51));
        resolve_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        resolve_btn.setForeground(new java.awt.Color(255, 255, 255));
        resolve_btn.setText("Resolved");
        resolve_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resolve_btn.setBorderPainted(false);
        resolve_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resolve_btn.setPreferredSize(new java.awt.Dimension(100, 30));
        resolve_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resolve_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resolve_btnMouseExited(evt);
            }
        });
        resolve_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolve_btnActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(106, 0, 212));
        back_btn.setText("<");
        back_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.setBorderPainted(false);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_btnMouseExited(evt);
            }
        });
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        tblMyQueries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "session id", "query", "faculty response", "follow up text", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMyQueries);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(fetch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 455, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(follow_up_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(resolve_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(fetch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(follow_up_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resolve_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void follow_up_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_follow_up_btnMouseEntered
        // TODO add your handling code here:
        follow_up_btn.setBackground(new Color(255,255,255));
        follow_up_btn.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_follow_up_btnMouseEntered

    private void follow_up_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_follow_up_btnMouseExited
        // TODO add your handling code here:
        follow_up_btn.setBackground(new Color(255,0,0));
        follow_up_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_follow_up_btnMouseExited

    private void follow_up_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_follow_up_btnActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblMyQueries.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a query first.");
        return;
    }

    String sessionId = tblMyQueries.getValueAt(selectedRow, 0).toString(); // Session ID
    String followUpMsg = JOptionPane.showInputDialog(this, "Enter your follow-up:");

    if (followUpMsg != null && !followUpMsg.trim().isEmpty()) {
        String sql = "UPDATE queries SET follow_up_text = ?, status = 'Follow-up', last_updated = NOW() WHERE session_id = ?";

        try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/clarity", "root", "");
             PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setString(1, followUpMsg);
            pst.setString(2, sessionId);

            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Follow-up submitted!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }


    }//GEN-LAST:event_follow_up_btnActionPerformed

    private void resolve_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resolve_btnMouseEntered
        // TODO add your handling code here:
        resolve_btn.setBackground(new Color(255,255,255));
        resolve_btn.setForeground(new Color(0,204,51));
    }//GEN-LAST:event_resolve_btnMouseEntered

    private void resolve_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resolve_btnMouseExited
        // TODO add your handling code here:
        resolve_btn.setBackground(new Color(0,204,51));
        resolve_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_resolve_btnMouseExited

    private void resolve_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolve_btnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMyQueries.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a query first.");
        return;
    }

    String sessionId = tblMyQueries.getValueAt(selectedRow, 0).toString();

    String sql = "UPDATE queries SET status = 'Resolved', last_updated = NOW() WHERE session_id = ?";

    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/clarity", "root", "");
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, sessionId);

        int rows = pst.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Query marked as resolved!");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }


    }//GEN-LAST:event_resolve_btnActionPerformed

    private void back_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnMouseEntered

    private void back_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnMouseExited

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        St_menu ob  = new St_menu();
        ob.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void fetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchActionPerformed
        // TODO add your handling code here:

    // ✅ Use the student ID stored at login
    String studentId = Datas.loggedInStudentId;

    if (studentId == null || studentId.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Student ID not found. Please log in again.");
        return;
    }

    String sql = "SELECT session_id, query_text, faculty_response, follow_up_text, status " +
                 "FROM queries WHERE student_id = ? ORDER BY submitted_at DESC";

    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/clarity", "root", "");
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, studentId);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tblMyQueries.getModel();
        model.setRowCount(0); // clear old data

        while (rs.next()) {
            String sessionId = rs.getString("session_id");
            String query = rs.getString("query_text");
            String facultyResp = rs.getString("faculty_response");
            String followUp = rs.getString("follow_up_text");
            String status = rs.getString("status");

            model.addRow(new Object[]{sessionId, query, facultyResp, followUp, status});
        }

        // ===== COLOR-CODE STATUS COLUMN =====
        tblMyQueries.getColumnModel().getColumn(4).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String status = value != null ? value.toString() : "";
                if (!isSelected) {
                    if (status.equalsIgnoreCase("Resolved")) {
                        c.setBackground(new Color(198, 239, 206)); // light green
                    } else if (status.equalsIgnoreCase("Follow-up")) {
                        c.setBackground(new Color(255, 235, 156)); // light yellow
                    } else {
                        c.setBackground(Color.WHITE);
                    }
                }
                return c;
            }
        });

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error fetching queries: " + e.getMessage());
    }

    }//GEN-LAST:event_fetchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new view_qs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton fetch;
    private javax.swing.JButton follow_up_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resolve_btn;
    private javax.swing.JTable tblMyQueries;
    // End of variables declaration//GEN-END:variables
}
