/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clarity.clarity;

import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ann Maria
 */
public class Yr_1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Yr_1.class.getName());

    /**
     * Creates new form Yr_1
     */
    public Yr_1() {
        initComponents();
        // ===== AUTO-RESIZE COLUMNS =====
    tblQueries.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    tblQueries.getColumnModel().getColumn(0).setPreferredWidth(80);  // Session ID
    tblQueries.getColumnModel().getColumn(1).setPreferredWidth(400); // Query
    tblQueries.getColumnModel().getColumn(2).setPreferredWidth(120); // Status

    // ===== WRAP TEXT IN QUERY COLUMN =====
    tblQueries.getColumnModel().getColumn(1).setCellRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            JTextArea textArea = new JTextArea(value != null ? value.toString() : "");
            textArea.setLineWrap(true);
            textArea.setWrapStyleWord(true);
            textArea.setOpaque(true);
            textArea.setFont(table.getFont()); // match table font
            if (isSelected) {
                textArea.setBackground(table.getSelectionBackground());
                textArea.setForeground(table.getSelectionForeground());
            } else {
                textArea.setBackground(table.getBackground());
                textArea.setForeground(table.getForeground());
            }
            return textArea;
        }
    });

    // ===== COLOR-CODE STATUS COLUMN =====
    tblQueries.getColumnModel().getColumn(2).setCellRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            String status = value != null ? value.toString() : "";
            if (!isSelected) { // only color if not selected
                if (status.equalsIgnoreCase("Resolved")) {
                    c.setBackground(new Color(198, 239, 206)); // light green
                } else if (status.equalsIgnoreCase("Follow-up")) {
                    c.setBackground(new Color(255, 235, 156)); // light yellow
                } else {
                    c.setBackground(Color.WHITE);
                }
            }
            return c;
        }
    });


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQueries = new javax.swing.JTable();
        fetchYr2 = new javax.swing.JButton();
        resolve_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(106, 0, 212));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 0, 212));
        jLabel1.setText("CLARITY");

        back_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(106, 0, 212));
        back_btn.setText("<");
        back_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.setBorderPainted(false);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.setPreferredSize(new java.awt.Dimension(30, 30));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 0, 212));
        jLabel2.setText("Year 1");

        tblQueries.setForeground(new java.awt.Color(106, 0, 212));
        tblQueries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Session ID", "Query", "follow up", "status", "date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblQueries);

        fetchYr2.setBackground(new java.awt.Color(106, 0, 212));
        fetchYr2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        fetchYr2.setForeground(new java.awt.Color(255, 255, 255));
        fetchYr2.setText("Fetch Details");
        fetchYr2.setToolTipText("");
        fetchYr2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fetchYr2.setBorderPainted(false);
        fetchYr2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fetchYr2.setPreferredSize(new java.awt.Dimension(175, 60));
        fetchYr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchYr2ActionPerformed(evt);
            }
        });

        resolve_btn.setBackground(new java.awt.Color(0, 204, 51));
        resolve_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        resolve_btn.setForeground(new java.awt.Color(255, 255, 255));
        resolve_btn.setText("Resolve");
        resolve_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resolve_btn.setBorderPainted(false);
        resolve_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resolve_btn.setPreferredSize(new java.awt.Dimension(100, 30));
        resolve_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resolve_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resolve_btnMouseExited(evt);
            }
        });
        resolve_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolve_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(279, 279, 279))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174)
                                .addComponent(jLabel1))
                            .addComponent(fetchYr2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resolve_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(fetchYr2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(resolve_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        Fac_menu ob = new Fac_menu();
        ob.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void fetchYr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchYr2ActionPerformed
        // TODO add your handling code here:
        String facultyName = Datas.loggedInFacultyName;
        String year = "1st Year"; // hardcoded for Yr_1 page

        String sql = "SELECT session_id, query_text, follow_up_text, status, submitted_at " +
        "FROM queries WHERE faculty_name = ? AND year = ? ORDER BY submitted_at DESC";

        try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/clarity", "root", "");
        PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, facultyName);
        pst.setString(2, year);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tblQueries.getModel();
        model.setRowCount(0); // clear old data

        while (rs.next()) {
            String sessionId = rs.getString("session_id");
            String query = rs.getString("query_text");
            String followUp = rs.getString("follow_up_text"); // ✅ new
            String status = rs.getString("status");
            Timestamp date = rs.getTimestamp("submitted_at");

            model.addRow(new Object[]{sessionId, query, followUp, status, date});
        }
        for (int row = 0; row < tblQueries.getRowCount(); row++) {
            int rowHeight = tblQueries.getRowHeight();

            Component comp = tblQueries.prepareRenderer(tblQueries.getCellRenderer(row, 1), row, 1);
            int preferredHeight = comp.getPreferredSize().height;

            if (preferredHeight > rowHeight) {
                tblQueries.setRowHeight(row, preferredHeight);
            }
        }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error fetching data: " + e.getMessage());
        }
    }//GEN-LAST:event_fetchYr2ActionPerformed

    private void resolve_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resolve_btnMouseEntered
        // TODO add your handling code here:
        resolve_btn.setBackground(new Color(255,255,255));
        resolve_btn.setForeground(new Color(0,204,51));
    }//GEN-LAST:event_resolve_btnMouseEntered

    private void resolve_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resolve_btnMouseExited
        // TODO add your handling code here:
        resolve_btn.setBackground(new Color(0,204,51));
        resolve_btn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_resolve_btnMouseExited

    private void resolve_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolve_btnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblQueries.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a query to resolve.");
            return;
        }

        String sessionId = tblQueries.getValueAt(selectedRow, 0).toString();
        String queryText = tblQueries.getValueAt(selectedRow, 1).toString();

        // ✅ Safely handle null follow-up
        Object followUpObj = tblQueries.getValueAt(selectedRow, 2);
        String followUp = (followUpObj != null) ? followUpObj.toString() : "";

        // ✅ Prefer follow-up if available
        String displayText = (!followUp.isEmpty()) ? followUp : queryText;

        Datas.selectedSessionId = sessionId;
        Datas.selectedQueryText = displayText;

        new FacultyRespond().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_resolve_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Yr_1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton fetchYr2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resolve_btn;
    private javax.swing.JTable tblQueries;
    // End of variables declaration//GEN-END:variables
}
